on:
  schedule:
    - cron: "*/2 * * * *" # run every two minutes

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
